image: alpine/edge
secrets:
  - fb389746-a44b-4ecc-9702-745977561e14
environment:
  REPO: grav-plugin-staticmath
  GH_USER: 9p4
tasks:
  - push-to-github: |
      cd ~/"${REPO}"
      git config --global credential.helper store
      git push --mirror "https://github.com/${GH_USER}/${REPO}"
