image: alpine/edge
secrets:
  - 5179ef46-70c0-4ece-9b67-dbf8dca2c37e
environment:
  REPO: grav-plugin-staticmath
  GH_USER: 9p4
tasks:
  - push-to-github: |
      cd ~/"${REPO}"
      git config --global credential.helper store
      git push --mirror "https://github.com/${GH_USER}/${REPO}"
