image: alpine/edge
secrets:
  - 4df836f8-5313-40b1-bc4e-b7b20cfd147e
environment:
  REPO: grav-plugin-staticmath
  GH_USER: 9p4
tasks:
  - push-to-github: |
      cd ~/"${REPO}"
      git config --global credential.helper store
      git push --mirror "https://github.com/${GH_USER}/${REPO}"
